# Generated by Django 3.2.8 on 2021-10-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20211009_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_expired',
            field=models.BooleanField(default=False, verbose_name='Is expired offer'),
        ),
    ]
